ALTER TABLE dba.users ALTER COLUMN username SET NOT NULL;
ALTER TABLE dba.users ALTER COLUMN password SET NOT NULL;
ALTER TABLE dba.users ALTER COLUMN email SET NOT NULL;
ALTER TABLE dba.users ALTER COLUMN role SET NOT NULL;